spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: passer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
