spring:
  boot:
    message: Hello, Department Service  Spring Cloud Demo!!!
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: passer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
