spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: passer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
