spring:

  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: passer
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    compatibility-verifier:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
